### PR TITLE
[#304] Display user name with email

### PR DESCRIPTION
**Pull request by Nika-code**
Created new user details class to keep track of nickname alongside of email after login and added the username to the navbar.
New user details class (CustomUserDetails.java) has to implement all UserDetails functions so the unused once were implemented only with return true logic (can be implemented later on when needed).
Now the navbar with username and email looks like this:
Screenshot 2024-10-03 170557

### CODE REVIEW

**Comment by Nika-code** [comment]
I will finish also tests refactoring to work with new implementation.

**Comment by fey** [comment]
@Nika-code hello, can you add dropdown menu, like in hexlet-cv, hexlet-sicp?

**Comment by Nika-code** [comment]
> @Nika-code hello, can you add dropdown menu, like in hexlet-cv, hexlet-sicp?

Can you send me what should the drop-down look like exactly? and what should be displayed when the drop-down is closed?

**Comment by Nika-code** [comment]
@fey Did you mean something like this?
Screenshot 2024-10-07 184636
Screenshot 2024-10-07 184718

**Comment by fey** [comment]
@Nika-code yes. And now you can move `logout` into menu =)

**Comment by Nika-code** [comment]
I've moved the logout button into the dropdown, now it looks like this (I've kept the hover color form the language dropdown to be consistent with styling)
Screenshot 2024-10-07 200405
Screenshot 2024-10-07 200533

**Comment by Malcom1986** [comment]
Можете пожалуйста на render задеплоить, чтобы можно было вживую попробовать

**Comment by Nika-code** [comment]
> Можете пожалуйста на render задеплоить, чтобы можно было вживую попробовать

@Malcom1986 what do you mean by this? 
I'm not sure I understand because there was nothing in the README about how to deploy the app. Did you mean I should just run command: make build?
Or can't you build my version locally?
If you should deploy the app somehow please explain to me how.

**Comment by shamshaev** [comment]
@Nika-code You can read about deploy here https://ru.hexlet.io/blog/posts/render-java. Please, be aware that Dockerfile already existing in project. You don't need to create it. Everything else - in article.

**Comment by Nika-code** [comment]
@Malcom1986 I've deployed my version of the app. Here is the link https://hexlet-correction-d3m7.onrender.com
Try it if it works

**Comment by Malcom1986** [comment]
Почему то 500 ошибка, можете посмотреть, что там призошло?

**Comment by Nika-code** [comment]
> Почему то 500 ошибка, можете посмотреть, что там призошло?

when did this error happen? Because I've tested the deployed version for signup and login on multiple devices and it worked correctly

**Comment by Malcom1986** [comment]
> > Почему то 500 ошибка, можете посмотреть, что там призошло?
> 
> @Malcom1986 when did this error happen? what were you doing? Because I've tested the deployed version for signup and login on multiple devices and it worked correctly

Регистрация и логин проходят успешно. Падает, когда я пытаюсь обновить данные пользователя - имя и фамилию

**Comment by Nika-code** [comment]
@Malcom1986 I fixed the issue, the new deployed version is available on the same link: https://hexlet-correction-d3m7.onrender.com

**Comment by Nika-code** [comment]
@Malcom1986 have you had time to check if the fix worked?

**Pull request merged**
